FROM linuxserver/syncthing

RUN mkdir -p /dockervolumes/logs
RUN chmod -R 777 /dockervolumes/logs

RUN mkdir -p /dockervolumes/homeassistant-config
RUN chmod -R 777 /dockervolumes/homeassistant-config