version: '3'
services: 
#################################################  
  can:
    container_name: CAN
    environment: 
      - TZ=Europe/Oslo
    build:
      context: .
      dockerfile: Dockerfile.CAN
    devices: 
      - /dev/gpiomem:/dev/gpiomem # GPIO pins with CAN Hat
    volumes: 
      - can-data:/can-data
#################################################
  temperature:
    container_name: Temperature
    environment: 
      - TZ=Europe/Oslo
    build:
      context: .
      dockerfile: Dockerfile.Temperature
    devices: 
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes: 
      - temperature-data:/temperature-data
    privileged: true
#################################################  
  homeassistant:
    container_name: HomeAssistant
    build:
      context: .
      dockerfile: Dockerfile.HomeAssistant
    environment: 
      - TZ=Europe/Oslo
    volumes: 
      - homeassistant-config:/config
      - can-data:/can-data:ro
      - temperature-data:/temperature-data:ro
    devices:
      - "/dev/ttyUSB1:/dev/ttyUSB0" # GPS
    network_mode: host
    restart: unless-stopped
    ports: 
      - 8123:8123
#################################################
  portainer:
    container_name: Portainer
    build:
      context: .
      dockerfile: Dockerfile.Portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports: 
      - 9000:9000
      - 8000:8000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
#################################################
  syncthing:
    container_name: Syncthing
    build:
      context: .
      dockerfile: Dockerfile.Syncthing
    restart: unless-stopped
    ports:
      - 8384:8384
      - 22000:22000
    volumes:
      - syncthing-config:/config
      - can-data:/dockervolumes/can-data
      - homeassistant-config:/dockervolumes/homeassistant-config
#################################################
  heimdall:
    container_name: Heimdall
    build:
      context: .
      dockerfile: Dockerfile.Heimdall
    environment:
      - TZ=Europe/Oslo
    volumes:
      - heimdall-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
#################################################
duckdns:
  container_name: DuckDNS
  build:
    context: .
    dockerfile: Dockerfile.DuckDNS
  env_file:
    - DuckDNS.env
  restart: unless-stopped
#################################################
volumes: 
  can-data:
  homeassistant-config:
  portainer-data:
  syncthing-config:
  heimdall-config:
  temperature-data: