version: '3'
services: 
#################################################  
  zigbee:
    container_name: ZigBee
    environment: 
      - TZ=Europe/Oslo
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=4430
      - DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2231183-if00
    build:
      context: .
      dockerfile: ./ZigBee/Dockerfile
    volumes: 
      - zigbee-config:/root/.local/share/dresden-elektronik/deCONZ
      - /dev:/dev
    privileged: true
#################################################  
  motor:
    container_name: Motor
    environment: 
      - TZ=Europe/Oslo
    build:
      context: .
      dockerfile: ./Motor/Dockerfile
    volumes: 
      - logs:/logs
      - /dev:/dev
    privileged: true
#################################################
  temperature:
    container_name: Temperature
    environment: 
      - TZ=Europe/Oslo
    build:
      context: .
      dockerfile: ./Temperature/Dockerfile
    volumes: 
      - logs:/logs
      - /dev:/dev
    privileged: true
#################################################
  orientation:
    container_name: Orientation
    environment: 
      - TZ=Europe/Oslo
    build:
      context: .
      dockerfile: ./Orientation/Dockerfile
    volumes: 
      - logs:/logs
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
#################################################  
  homeassistant:
    container_name: HomeAssistant
    build:
      context: .
      dockerfile: ./HomeAssistant/Dockerfile
    environment: 
      - TZ=Europe/Oslo
    volumes: 
      - homeassistant-config:/config
      - logs:/logs:ro
    network_mode: host
    restart: unless-stopped
    ports: 
      - 8123:8123
#################################################
  portainer:
    container_name: Portainer
    build:
      context: .
      dockerfile: ./Portainer/Dockerfile
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports: 
      - 9000:9000
      - 8000:8000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
#################################################
  syncthing:
    container_name: Syncthing
    build:
      context: .
      dockerfile: ./Syncthing/Dockerfile
    restart: unless-stopped
    ports:
      - 8384:8384
      - 22000:22000
    volumes:
      - syncthing-config:/config
      - logs:/logs
      - homeassistant-config:/dockervolumes/homeassistant-config
#################################################
  heimdall:
    container_name: Heimdall
    build:
      context: .
      dockerfile: ./Heimdall/Dockerfile
    environment:
      - TZ=Europe/Oslo
    volumes:
      - heimdall-config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
#################################################
  duckdns:
    container_name: DuckDNS
    build:
      context: .
      dockerfile: ./DuckDNS/Dockerfile
    env_file:
      - ./DuckDNS/DuckDNS.env
    restart: unless-stopped
#################################################
  code-server:
    container_name: Code-Server
    build:
      context: .
      dockerfile: ./Code-Server/Dockerfile
    volumes:
      - code-server-config:/config
      - homeassistant-config:/dockervolumes/homeassistant-config
    ports: 
      - "8443:8443"
    environment:
      - PUID=0
      - PGID=0
    restart: unless-stopped
#################################################
volumes: 
  logs:
  homeassistant-config:
  portainer-data:
  syncthing-config:
  heimdall-config:
  code-server-config:
  zigbee-config: