FROM mcr.microsoft.com/powershell:lts-arm32v7-ubuntu-bionic

RUN apt-get update && apt-get install can-utils -y
RUN mkdir /logs

ADD ParseCAN.ps1 /app/

ENTRYPOINT [ "pwsh", "-File", "/app/ParseCAN.ps1" ]