FROM linuxserver/syncthing

RUN mkdir -p /dockervolumes/can-data
RUN chmod -R 777 /dockervolumes/can-data

RUN mkdir -p /dockervolumes/homeassistant-config
RUN chmod -R 777 /dockervolumes/homeassistant-config