version: '3'
services: 
  can:
    container_name: CAN
    build:
      context: .
      dockerfile: Dockerfile.CAN
    devices: 
      - /dev/gpiomem
    volumes: 
      - can-data:/can-data
    restart: unless-stopped
  homeassistant:
    container_name: HomeAssistant
    environment: 
      - TZ=Europe/Oslo
    volumes: 
      - homeassistant-config:/config
      - can-data:/can-data:ro
    network_mode: host
    image: homeassistant/raspberrypi3-homeassistant:stable
    restart: unless-stopped
    ports: 
      - 8123:8123
  portainer:
    container_name: Portainer
    image: portainer/portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports: 
      - 9000:9000
      - 8000:8000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
volumes: 
  can-data:
  homeassistant-config:
  portainer-data: