version: '3.8'
services:
    batteryserver:
        ports:
            - '80:5000'
        devices:
            - '/dev/i2c-1:/dev/i2c-1'
        restart: unless-stopped
        privileged: true
        container_name: batteryserver
        image: batteryserver