title: Boat Assistant
views:
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: sensor.gps_speed_knots
                max: 10
                min: 0
                severity:
                  green: 0
                  red: 8
                  yellow: 5
                type: gauge
              - entity: sensor.motor_rpm
                max: 5000
                min: 0
                name: Motor
                severity:
                  green: 0
                  red: 4000
                  yellow: 2000
                type: gauge
              - entity: sensor.motor_amp
                max: 200
                min: 0
                name: Motor
                severity:
                  green: 0
                  red: 150
                  yellow: 75
                type: gauge
              - entity: sensor.motor_temp
                max: 100
                min: 0
                name: Motor
                severity:
                  green: 0
                  red: 75
                  yellow: 50
                type: gauge
              - entity: sensor.battery_volt
                max: 60
                min: 48
                name: Motor
                type: gauge
            type: horizontal-stack
          - cards:
              - entity: sensor.water_temperature
                max: 30
                min: 0
                name: Fjord
                type: gauge
              - entity: sensor.multi_sensor
                max: 30
                min: 0
                type: gauge
              - entity: sensor.bilge_temperature
                max: 30
                min: 0
                name: Bilge
                type: gauge
            type: horizontal-stack
          - cards:
              - type: vertical-stack
                cards:
                  - type: gauge
                    entity: sensor.pitch_degrees
                    min: 0
                    max: 25
                    severity:
                      green: 0
                      yellow: 5
                      red: 15
                  - type: markdown
                    content: >-
                      <center> <ha-icon icon="mdi:arrow-{{
                      states.sensor.orientation.attributes.pitchDirection
                      }}"></ha-icon> </center>
              - type: vertical-stack
                cards:
                  - type: gauge
                    entity: sensor.roll_degrees
                    min: 0
                    max: 25
                    severity:
                      green: 0
                      yellow: 5
                      red: 15
                  - type: markdown
                    content: >-
                      <center> <ha-icon icon="mdi:arrow-{{
                      states.sensor.orientation.attributes.rollDirection
                      }}"></ha-icon> </center>
            type: horizontal-stack
          - cards:
              - type: button
                tap_action:
                  action: more-info
                entity: binary_sensor.water_5
                show_state: true
                show_name: true
                show_icon: true
                icon_height: 80px
                hold_action:
                  action: none
              - type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.wifirelay1
                entity: switch.wifirelay1
                icon: 'mdi:water-pump'
                show_state: false
                name: Turn on pump
                hold_action:
                  action: none
                icon_height: 80px
              - type: button
                tap_action:
                  action: call-service
                  service: switch.turn_off
                  service_data:
                    entity_id: switch.wifirelay1
                entity: switch.wifirelay1
                name: Turn off pump
                icon: 'mdi:water-pump-off'
                hold_action:
                  action: none
                icon_height: 80px
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:anchor'
    panel: true
    path: main
    title: Main
  - badges: []
    cards:
      - cards:
          - entity: sensor.tl_mr3020_kib_s_received
            graph: line
            hours_to_show: 12
            icon: 'mdi:signal-3g'
            name: Download
            type: sensor
          - entity: sensor.tl_mr3020_kib_s_sent
            graph: line
            hours_to_show: 12
            icon: 'mdi:signal-3g'
            name: Upload
            type: sensor
        type: horizontal-stack
      - cards:
          - entity: sensor.processor_use
            max: 100
            min: 0
            name: CPU
            severity:
              green: 0
              red: 75
              yellow: 50
            type: gauge
          - entity: sensor.memory_use_percent
            max: 100
            min: 0
            name: RAM
            severity:
              green: 0
              red: 75
              yellow: 50
            type: gauge
          - entity: sensor.disk_use_percent
            max: 100
            min: 0
            name: Storage
            severity:
              green: 0
              red: 75
              yellow: 50
            type: gauge
          - entity: sensor.cpu_temperature
            max: 100
            min: 0
            name: Temp
            severity:
              green: 0
              red: 70
              yellow: 50
            type: gauge
        type: horizontal-stack
    icon: 'mdi:cogs'
    path: system
    title: system
